export const teams: any = [
  { name: 'SUPRESSÃO VEGETAL / ACESSOS 1', tooling_cost: 0 },
  { name: 'SUPRESSÃO VEGETAL / ACESSOS 2', tooling_cost: 0 },
  { name: 'ABERTURA DE FAIXA DE SERVIDÃO / ÁREA DE TORRE 1', tooling_cost: 0 },
  { name: 'ABERTURA DE FAIXA DE SERVIDÃO / ÁREA DE TORRE 2', tooling_cost: 0 },
  { name: 'ATERRAMENTO E SECCIONAMENTO DE CERCAS 1', tooling_cost: 0 },
  { name: 'ATERRAMENTO E SECCIONAMENTO DE CERCAS 2', tooling_cost: 0 },
  { name: 'TOPOGRAFIA - LOCAÇÃO DE TORRE 1', tooling_cost: 0 },
  { name: 'TOPOGRAFIA - LOCAÇÃO DE TORRE 2', tooling_cost: 0 },
  { name: 'CONFERÊNCIA DE PERFIL 1', tooling_cost: 0 },
  { name: 'CONFERÊNCIA DE PERFIL 2', tooling_cost: 0 },
  { name: 'SONDAGEM 1', tooling_cost: 0 },
  { name: 'SONDAGEM 2', tooling_cost: 0 },
  { name: 'MARCAÇÃO DE CAVAS 1', tooling_cost: 0 },
  { name: 'MARCAÇÃO DE CAVAS 2', tooling_cost: 0 },
  { name: 'ESCAVAÇÃO 1', tooling_cost: 0 },
  { name: 'ESCAVAÇÃO 2', tooling_cost: 0 },
  { name: 'PREPARAÇÃO E CONCRETAGEM 1', tooling_cost: 0 },
  { name: 'PREPARAÇÃO E CONCRETAGEM 2', tooling_cost: 0 },
  { name: 'ARMAÇÃO 1', tooling_cost: 0 },
  { name: 'ARMAÇÃO 2', tooling_cost: 0 },
  { name: 'DESFORMA 1', tooling_cost: 0 },
  { name: 'PÁTIO CONCRETO PRÉ MOLDADO 1', tooling_cost: 0 },
  { name: 'PÁTIO CONCRETO PRÉ MOLDADO 2', tooling_cost: 0 },
  { name: 'REATERRO 1', tooling_cost: 0 },
  { name: 'REATERRO 2', tooling_cost: 0 },
  { name: 'INSTALAÇÃO E NIVELAMENTO BLOCOS PREMOLDADOS 1', tooling_cost: 0 },
  { name: 'LABORATÓRIO - ROMPIMENTO CORPO DE PROVA 1', tooling_cost: 0 },
  { name: 'MONTAGEM DE CANTEIRO 1', tooling_cost: 0 },
  { name: 'CRAVAÇÃO DAS ESTACAS 1', tooling_cost: 0 },
  { name: 'INSTALAÇÃO DE TIRANTES HELICOIDAL 1', tooling_cost: 0 },
  { name: 'ENSAIO DE ARRANCAMENTO 1', tooling_cost: 0 },
  { name: 'PRÉ-MONTAGEM 1', tooling_cost: 0 },
  { name: 'PRÉ-MONTAGEM 2', tooling_cost: 0 },
  { name: 'PRÉ-MONTAGEM 3', tooling_cost: 0 },
  { name: 'MONTAGEM GUINDASTE 1', tooling_cost: 0 },
  { name: 'MONTAGEM GUINDASTE 2', tooling_cost: 0 },
  { name: 'MONTAGEM MANUAL 1', tooling_cost: 0 },
  { name: 'MONTAGEM MANUAL 2', tooling_cost: 0 },
  { name: 'REVISÃO 1', tooling_cost: 0 },
  { name: 'REVISÃO 2', tooling_cost: 0 },
  { name: 'REVISÃO 3', tooling_cost: 0 },
  { name: 'GIRO E PRUMO 1', tooling_cost: 0 },
  { name: 'GIRO E PRUMO 2', tooling_cost: 0 },
  { name: 'IÇAMENTO 1', tooling_cost: 0 },
  { name: 'IÇAMENTO 2', tooling_cost: 0 },
  { name: 'TRANSPORTE DE TORRES 1', tooling_cost: 0 },
  { name: 'TRANSPORTE DE TORRES 2', tooling_cost: 0 },
  { name: 'INSTALAÇÃO CONTRAPESO 1', tooling_cost: 0 },
  { name: 'INSTALAÇÃO CONTRAPESO 2', tooling_cost: 0 },
  { name: 'MEDIÇÃO DE RESISTÊNCIA 1', tooling_cost: 0 },
  { name: 'MEDIÇÃO DE RESISTÊNCIA 2', tooling_cost: 0 },
  { name: 'LANÇAMENTO E REGULAGEM DE CABOS OPGW 1', tooling_cost: 0 },
  { name: 'LANÇAMENTO E REGULAGEM DE CABOS OPGW 2', tooling_cost: 0 },
  {
    name: 'LANÇAMENTO E REGULAGEM DE CABOS PÁRA-RAIOS 3/8" 1',
    tooling_cost: 0,
  },
  {
    name: 'LANÇAMENTO E REGULAGEM DE CABOS PÁRA-RAIOS 3/8" 2',
    tooling_cost: 0,
  },
  { name: 'TRANSPORTE DE BOBINAS E ACESSÓRIOS 1', tooling_cost: 0 },
  { name: 'TRANSPORTE DE BOBINAS E ACESSÓRIOS 2', tooling_cost: 0 },
  { name: 'INSTALAÇÃO DE CAVALETES 1', tooling_cost: 0 },
  { name: 'INSTALAÇÃO DE CAVALETES 2', tooling_cost: 0 },
  { name: 'IÇAMENTO DE BANDOLAS 1', tooling_cost: 0 },
  { name: 'IÇAMENTO DE BANDOLAS 2', tooling_cost: 0 },
  { name: 'LANÇAMENTO DE CABO PILOTO 1', tooling_cost: 0 },
  { name: 'LANÇAMENTO DE CABO PILOTO 2', tooling_cost: 0 },
  { name: 'LANÇAMENTO DE CABO CONDUTOR 1', tooling_cost: 0 },
  { name: 'LANÇAMENTO DE CABO CONDUTOR 2', tooling_cost: 0 },
  { name: 'LANÇAMENTO DE CABO CONDUTOR - PULLER 1', tooling_cost: 0 },
  { name: 'LANÇAMENTO DE CABO CONDUTOR - PULLER 2', tooling_cost: 0 },
  { name: 'ACOMPANHAMENTO DE ARRAIA 1', tooling_cost: 0 },
  { name: 'ACOMPANHAMENTO DE ARRAIA 2', tooling_cost: 0 },
  { name: 'NIVELAMENTO DE CABOS CONDUTOR 1', tooling_cost: 0 },
  { name: 'NIVELAMENTO DE CABOS CONDUTOR 2', tooling_cost: 0 },
  { name: 'GRAMPEAÇÃO E ANCORAGEM 1', tooling_cost: 0 },
  { name: 'GRAMPEAÇÃO E ANCORAGEM 2', tooling_cost: 0 },
  { name: 'ESPAÇADOR - JUMPERS 1', tooling_cost: 0 },
  { name: 'ESPAÇADOR - JUMPERS 2', tooling_cost: 0 },
  { name: 'REVISÃO FINAL 1', tooling_cost: 0 },
  { name: 'REVISÃO FINAL 2', tooling_cost: 0 },
  { name: 'REVISÃO DE SOLO 1', tooling_cost: 0 },
  { name: 'REVISÃO DE SOLO 2', tooling_cost: 0 },
  { name: 'COMISSINAMENTO 1', tooling_cost: 0 },
  { name: 'COMISSINAMENTO 2', tooling_cost: 0 },
  { name: 'INSS', tooling_cost: 0 },
  { name: 'À DISPOSIÇÃO', tooling_cost: 0 },
  { name: 'FÉRIAS', tooling_cost: 0 },
];
