export const mockedDiagramList = [
  {
    backfill_volume: 1212,
    code: 1,
    comments: 'comments',
    concrete_volume: 1212,
    coordinates: test,
    createdAt: new Date(),
    embargo: 'FUNDIARIO',
    excavation_volume: 1212,
    forward: 1212,
    height: 1212,
    id: 1,
    locality: test,
    status_cable_laying: 'test',
    status_foundation_A: 'test',
    status_foundation_B: 'test',
    status_foundation_C: 'test',
    status_foundation_D: 'test',
    status_foundation_MC: 'test',
    status_topography: 'test',
    status_tower_assembly: 'test',
    status_vegetal_suppression: 'test',
    steel_volume: 1212,
    tower: '12/2',
    type: 'some type',
    type_of_foundation_A: 'A',
    type_of_foundation_B: 'B',
    type_of_foundation_C: 'C',
    type_of_foundation_D: 'D',
    type_of_foundation_MC: 'MC',
    updatedAt: new Date(),
    weight: 1212,
  },
  {
    backfill_volume: 333,
    code: 2,
    comments: 'comments',
    concrete_volume: 2222,
    coordinates: test,
    createdAt: new Date(),
    embargo: 'FUNDIARIO',
    excavation_volume: 1212,
    forward: 1212,
    height: 1212,
    id: 1,
    locality: test,
    status_cable_laying: 'test',
    status_foundation_A: 'test',
    status_foundation_B: 'test',
    status_foundation_C: 'test',
    status_foundation_D: 'test',
    status_foundation_MC: 'test',
    status_topography: 'test',
    status_tower_assembly: 'test',
    status_vegetal_suppression: 'test',
    steel_volume: 1212,
    tower: '12/3',
    type: 'some type',
    type_of_foundation_A: 'A',
    type_of_foundation_B: 'B',
    type_of_foundation_C: 'C',
    type_of_foundation_D: 'D',
    type_of_foundation_MC: 'MC',
    updatedAt: new Date(),
    weight: 1212,
  },
];
